#!/usr/bin/env ruby

# Pseudo-random sequence generated by entirely a deterministic casual
# process with pseudo random generator built into Ruby

require_relative '../generator.rb'

class Deterministic < Generator
  def initialize(*args)
    super(*args)
    @r = Random.new(5)  # chosen by fair dice roll
  end

  def self.summary
   "Deterministic pseudo random number generator built into Ruby"
  end

  def self.description
    desc = <<-DESC_END
      This generator uses Ruby's built-in PRNG with a deterministic seed to
      produce data.
    DESC_END
    desc.gsub(/\s+/, " ").strip
  end


  def next_chunk
    [ @r.rand(2**32) ].pack('L>')
  end

end

Deterministic.run if __FILE__ == $0
